import type { PatientRecord } from './patientRecordStore';

export const MOCK_PATIENTS: PatientRecord[] = [

  {
    caseId: 'BraTS2021_00000',
    name: 'Zhang Wei',
    age: 52,
    gender: 'M',
    bloodType: 'A+',
    phone: '138-0000-0001',
    email: 'zhangwei@example.com',
    address: '301 Neurology Ward, Beijing Tiantan Hospital',
    emergencyContact: 'Li Fang (wife) 139-0000-0010',
    admissionDate: '2024-11-03',
    primaryDiagnosis: 'Glioblastoma multiforme (GBM), WHO Grade IV',
    medicalRecordNumber: 'MRN-2024-00001',
    height: 172,
    weight: 68,
    chiefComplaint: 'Progressive headache and left-sided weakness for 3 weeks',
    presentIllness:
      'Mr. Zhang is a 52-year-old male who presented with a 3-week history of progressively worsening bifrontal headaches, most severe in the morning. Associated with nausea and one episode of projectile vomiting. He developed progressive left upper extremity weakness over 2 weeks, with difficulty grasping objects. One episode of witnessed generalized tonic-clonic seizure 5 days prior to admission, lasting approximately 2 minutes with post-ictal confusion for 30 minutes. He also reports mild word-finding difficulty and recent personality changes noted by family.',
    familyHistory:
      'Father: colon cancer at age 68, deceased at 72. Mother: hypertension, alive. One sibling, healthy. No known hereditary cancer syndromes.',
    socialHistory:
      'Non-smoker. Occasional social alcohol. High school teacher. Married with one adult child. No illicit drug use.',
    tumorInfo: {
      location: 'Right temporal lobe with extension to parietal lobe',
      laterality: 'right',
      size: '5.2 × 4.1 × 3.8 cm',
      whoGrade: 'IV',
      histology: 'Glioblastoma, IDH-wildtype',
      molecularMarkers: {
        'IDH1/2': 'Wildtype',
        'MGMT Promoter': 'Methylated',
        '1p/19q': 'Intact',
        'ATRX': 'Retained',
        'p53': 'Mutant (~30%)',
        'EGFR': 'Amplified',
        'Ki-67': '35%',
        'TERT Promoter': 'Mutant',
      },
      kps: 80,
    },
    treatmentPlans: [
      { id: 'tp1', name: 'Maximal Safe Resection', type: 'surgery', status: 'completed', startDate: '2024-11-08', endDate: '2024-11-08', protocol: 'Right temporal craniotomy with neuronavigation-guided GTR', notes: 'GTR confirmed on post-op MRI. EBL 250 mL. No new deficits.' },
      { id: 'tp2', name: 'Concurrent Chemoradiation (Stupp)', type: 'radiation', status: 'active', startDate: '2024-11-25', endDate: '2025-01-05', protocol: 'IMRT 60 Gy / 30 fractions + TMZ 75 mg/m²/day', notes: 'Week 3 of 6. Tolerating well.' },
      { id: 'tp3', name: 'Adjuvant TMZ', type: 'chemotherapy', status: 'planned', startDate: '2025-01-20', protocol: 'TMZ 150-200 mg/m², 5/28 days × 6 cycles', cycles: 6, completedCycles: 0, notes: 'Dose escalation to 200 mg/m² from cycle 2 if tolerated.' },
    ],
    labResults: [
      { id: 'l1', date: '2024-11-03', category: 'Hematology', testName: 'WBC', value: '7.2', unit: '×10⁹/L', referenceRange: '4.0–11.0', abnormal: false },
      { id: 'l2', date: '2024-11-03', category: 'Hematology', testName: 'Hemoglobin', value: '14.1', unit: 'g/dL', referenceRange: '13.5–17.5', abnormal: false },
      { id: 'l3', date: '2024-11-03', category: 'Hematology', testName: 'Platelets', value: '198', unit: '×10⁹/L', referenceRange: '150–400', abnormal: false },
      { id: 'l4', date: '2024-11-03', category: 'Chemistry', testName: 'Creatinine', value: '0.9', unit: 'mg/dL', referenceRange: '0.7–1.3', abnormal: false },
      { id: 'l5', date: '2024-11-03', category: 'Chemistry', testName: 'ALT', value: '28', unit: 'U/L', referenceRange: '7–56', abnormal: false },
      { id: 'l6', date: '2024-11-20', category: 'Hematology', testName: 'ANC', value: '3.2', unit: '×10⁹/L', referenceRange: '1.5–8.0', abnormal: false },
      { id: 'l7', date: '2024-11-20', category: 'Chemistry', testName: 'Glucose (fasting)', value: '128', unit: 'mg/dL', referenceRange: '70–100', abnormal: true },
    ],
    imagingStudies: [
      { id: 'img1', date: '2024-11-03', modality: 'MRI Brain', sequences: ['T1', 'T1+Gd', 'T2', 'FLAIR', 'DWI', 'SWI'], findings: 'Large heterogeneously enhancing mass in right temporal lobe (5.2×4.1×3.8 cm) with central necrosis, surrounding FLAIR hyperintensity. 8 mm rightward midline shift.', impression: 'High-grade glioma (GBM) of right temporal lobe. Recommend neurosurgical consultation.', linkedCaseId: 'BraTS2021_00000' },
      { id: 'img2', date: '2024-11-10', modality: 'MRI Brain Post-op', sequences: ['T1', 'T1+Gd', 'T2', 'FLAIR', 'DWI'], findings: 'Post-craniotomy changes, no residual enhancing tumor. Reduced midline shift to 2 mm.', impression: 'Gross total resection achieved. Expected post-op changes.', linkedCaseId: 'BraTS2021_00000' },
    ],
    allergies: [
      { id: 'a1', allergen: 'Sulfonamides', reaction: 'Skin rash, urticaria', severity: 'moderate' },
    ],
    comorbidities: [
      { id: 'c1', condition: 'Essential hypertension', onset: '2018', status: 'controlled', notes: 'Amlodipine 5 mg daily' },
      { id: 'c2', condition: 'Type 2 diabetes mellitus', onset: '2020', status: 'controlled', notes: 'Metformin 500 mg BID, HbA1c 6.8%' },
    ],
    medications: [
      { id: 'm1', name: 'Temozolomide', dosage: '200 mg (75 mg/m²)', frequency: 'Daily during RT', startDate: '2024-11-25', notes: 'Stupp concurrent phase' },
      { id: 'm2', name: 'Dexamethasone', dosage: '4 mg', frequency: 'BID', startDate: '2024-11-05', endDate: '2024-12-01', notes: 'Taper after edema reduction' },
      { id: 'm3', name: 'Levetiracetam', dosage: '500 mg', frequency: 'BID', startDate: '2024-11-04', notes: 'Seizure prophylaxis' },
      { id: 'm4', name: 'Amlodipine', dosage: '5 mg', frequency: 'Daily', startDate: '2018-06-15', notes: 'Hypertension' },
      { id: 'm5', name: 'Metformin', dosage: '500 mg', frequency: 'BID', startDate: '2020-03-01', notes: 'Type 2 DM' },
      { id: 'm6', name: 'TMP-SMX DS', dosage: '1 tablet', frequency: 'MWF', startDate: '2024-11-25', notes: 'PJP prophylaxis during TMZ' },
      { id: 'm7', name: 'Omeprazole', dosage: '20 mg', frequency: 'Daily', startDate: '2024-11-05', notes: 'GI protection w/ dexamethasone' },
    ],
    visits: [
      { id: 'v1', date: '2024-11-03', department: 'Neurosurgery', doctor: 'Dr. Wang Jian', diagnosis: 'Admission for craniotomy evaluation', notes: 'MRI shows large right temporal mass with midline shift' },
      { id: 'v2', date: '2024-11-08', department: 'Neurosurgery', doctor: 'Dr. Wang Jian', diagnosis: 'Right temporal craniotomy – GTR', notes: 'Gross total resection achieved. No new deficits.' },
      { id: 'v3', date: '2024-11-10', department: 'Neurosurgery', doctor: 'Dr. Wang Jian', diagnosis: 'Post-op day 2, MRI review', notes: 'MRI confirms GTR. Plan discharge.' },
      { id: 'v4', date: '2024-11-15', department: 'Neuro-oncology', doctor: 'Dr. Chen Li', diagnosis: 'Pathology: GBM IDH-wt WHO IV', notes: 'MGMT methylated. Stupp protocol planned.' },
      { id: 'v5', date: '2024-11-25', department: 'Radiation Oncology', doctor: 'Dr. Yang Bo', diagnosis: 'Started concurrent chemoradiation', notes: 'IMRT 60 Gy/30 fx + TMZ 75 mg/m²' },
    ],
    files: [],
  },

  {
    caseId: 'BraTS2021_00002',
    name: 'Maria Garcia',
    age: 45,
    gender: 'F',
    bloodType: 'O+',
    phone: '138-0000-0002',
    email: 'mgarcia@example.com',
    address: '205 Oncology Ward, Huashan Hospital',
    emergencyContact: 'Carlos Garcia (husband) 139-0000-0020',
    admissionDate: '2024-10-15',
    primaryDiagnosis: 'Anaplastic Astrocytoma, WHO Grade III, IDH-mutant',
    medicalRecordNumber: 'MRN-2024-00002',
    height: 163,
    weight: 58,
    chiefComplaint: 'Recurrent seizures for 2 months and progressive word-finding difficulty',
    presentIllness:
      'Ms. Garcia is a 45-year-old female presenting with new-onset seizures beginning 2 months ago. Seizures are focal with secondary generalization, occurring 2–3 times per week despite levetiracetam initiation by her local neurologist. She also reports progressive word-finding difficulty, difficulty reading, and right hand clumsiness over the past 6 weeks. No headache, no nausea/vomiting, no vision changes.',
    familyHistory:
      'Mother: breast cancer at 55, alive after treatment. Father: healthy. No family history of brain tumors or neurogenetic syndromes.',
    socialHistory:
      'Never smoker. Rare social alcohol. Graphic designer. Married. No children. No illicit drug use.',
    tumorInfo: {
      location: 'Left frontal lobe involving Broca area',
      laterality: 'left',
      size: '3.8 × 3.2 × 2.9 cm',
      whoGrade: 'III',
      histology: 'Anaplastic Astrocytoma, IDH-mutant',
      molecularMarkers: {
        'IDH1': 'R132H Mutant',
        'MGMT Promoter': 'Methylated',
        '1p/19q': 'Intact',
        'ATRX': 'Lost',
        'p53': 'Mutant (~60%)',
        'Ki-67': '20%',
        'TERT Promoter': 'Wildtype',
      },
      kps: 90,
    },
    treatmentPlans: [
      { id: 'tp4', name: 'Awake Craniotomy', type: 'surgery', status: 'completed', startDate: '2024-10-20', endDate: '2024-10-20', protocol: 'Left frontal awake craniotomy with intraoperative language mapping', notes: 'Near-total resection. Small residual at eloquent cortex. No aphasia post-op.' },
      { id: 'tp5', name: 'Adjuvant RT + TMZ', type: 'radiation', status: 'active', startDate: '2024-11-10', protocol: 'IMRT 59.4 Gy / 33 fx + concurrent TMZ 75 mg/m²/day', notes: 'Fraction 15 of 33. No significant toxicity.' },
      { id: 'tp6', name: 'Adjuvant TMZ Maintenance', type: 'chemotherapy', status: 'planned', startDate: '2025-01-05', protocol: 'TMZ 150-200 mg/m² × 12 cycles', cycles: 12, completedCycles: 0, notes: 'IDH-mutant AA: extended adjuvant TMZ recommended.' },
    ],
    labResults: [
      { id: 'l8',  date: '2024-10-15', category: 'Hematology', testName: 'WBC', value: '6.5', unit: '×10⁹/L', referenceRange: '4.0–11.0', abnormal: false },
      { id: 'l9',  date: '2024-10-15', category: 'Hematology', testName: 'Hemoglobin', value: '12.8', unit: 'g/dL', referenceRange: '12.0–16.0', abnormal: false },
      { id: 'l10', date: '2024-10-15', category: 'Hematology', testName: 'Platelets', value: '245', unit: '×10⁹/L', referenceRange: '150–400', abnormal: false },
      { id: 'l11', date: '2024-11-12', category: 'Hematology', testName: 'ANC', value: '2.8', unit: '×10⁹/L', referenceRange: '1.5–8.0', abnormal: false },
      { id: 'l12', date: '2024-11-12', category: 'Chemistry', testName: 'ALT', value: '35', unit: 'U/L', referenceRange: '7–45', abnormal: false },
    ],
    imagingStudies: [
      { id: 'img3', date: '2024-10-15', modality: 'MRI Brain', sequences: ['T1', 'T1+Gd', 'T2', 'FLAIR', 'DWI', 'MRS'], findings: 'Non-enhancing FLAIR hyperintense mass in left frontal lobe (3.8×3.2×2.9 cm) with elevated choline on MRS. Minimal mass effect.', impression: 'Left frontal mass consistent with diffuse glioma, likely Grade II-III.', linkedCaseId: 'BraTS2021_00002' },
      { id: 'img4', date: '2024-10-22', modality: 'MRI Brain Post-op', sequences: ['T1', 'T1+Gd', 'FLAIR'], findings: 'Post-craniotomy changes. Small residual FLAIR abnormality at posterior margin near Broca area. No new enhancement.', impression: 'Near-total resection. Small residual at eloquent cortex.', linkedCaseId: 'BraTS2021_00002' },
    ],
    allergies: [
      { id: 'a2', allergen: 'Penicillin', reaction: 'Anaphylaxis (reported)', severity: 'severe' },
    ],
    comorbidities: [
      { id: 'c3', condition: 'Chronic migraine', onset: '2015', status: 'controlled', notes: 'Topiramate 50 mg daily' },
    ],
    medications: [
      { id: 'm8', name: 'Temozolomide', dosage: '150 mg (75 mg/m²)', frequency: 'Daily during RT', startDate: '2024-11-10', notes: 'Concurrent with radiotherapy' },
      { id: 'm9', name: 'Levetiracetam', dosage: '750 mg', frequency: 'BID', startDate: '2024-10-10', notes: 'Seizure control' },
      { id: 'm10', name: 'Ondansetron', dosage: '8 mg', frequency: 'PRN', startDate: '2024-11-10', notes: 'Anti-emetic for chemo' },
      { id: 'm11', name: 'Topiramate', dosage: '50 mg', frequency: 'Daily', startDate: '2015-06-01', notes: 'Migraine prophylaxis' },
    ],
    visits: [
      { id: 'v6', date: '2024-10-15', department: 'Neurology', doctor: 'Dr. Liu Mei', diagnosis: 'Recurrent seizures, MRI shows left frontal mass', notes: 'Referred to neurosurgery' },
      { id: 'v7', date: '2024-10-20', department: 'Neurosurgery', doctor: 'Dr. Zhao Peng', diagnosis: 'Awake craniotomy – NTR', notes: 'Near-total resection. Language preserved.' },
      { id: 'v8', date: '2024-10-28', department: 'Neuro-oncology', doctor: 'Dr. Chen Li', diagnosis: 'Path: AA III, IDH-mutant', notes: 'MGMT methylated. Planned RT+TMZ.' },
    ],
    files: [],
  },

  {
    caseId: 'BraTS2021_00003',
    name: 'James Thompson',
    age: 63,
    gender: 'M',
    bloodType: 'B+',
    phone: '138-0000-0003',
    email: 'jthompson@example.com',
    address: '412 ICU Step-down, PUMCH',
    emergencyContact: 'Sarah Thompson (daughter) 139-0000-0030',
    admissionDate: '2024-09-28',
    primaryDiagnosis: 'Glioblastoma multiforme, recurrent (first recurrence)',
    medicalRecordNumber: 'MRN-2024-00003',
    height: 178,
    weight: 82,
    chiefComplaint: 'Acute onset right hemiparesis and expressive aphasia',
    presentIllness:
      'Mr. Thompson is a 63-year-old male with known GBM of the left parietal lobe (initially diagnosed 2024-03, s/p GTR and completed Stupp protocol). Presented to ER with sudden-onset right-sided weakness and slurred speech over 6 hours. CT head showed new enhancing mass at the prior resection cavity margin. MRI confirmed recurrence with 3.5 cm mass, new enhancement, and increased edema.',
    familyHistory: 'No family history of cancer. Mother had Alzheimer disease at 75.',
    socialHistory: 'Former smoker (20 pack-years, quit 2015). Occasional beer. Retired accountant. Widower. Lives alone.',
    tumorInfo: {
      location: 'Left parietal lobe (resection cavity margin)',
      laterality: 'left',
      size: '3.5 × 3.0 × 2.8 cm',
      whoGrade: 'IV',
      histology: 'Glioblastoma, IDH-wildtype, recurrent',
      molecularMarkers: {
        'IDH1/2': 'Wildtype',
        'MGMT Promoter': 'Unmethylated',
        '1p/19q': 'Intact',
        'EGFR': 'Amplified (EGFRvIII positive)',
        'Ki-67': '40%',
        'TERT Promoter': 'Mutant',
        'PTEN': 'Loss',
        'CDKN2A': 'Homozygous deletion',
      },
      kps: 60,
    },
    treatmentPlans: [
      { id: 'tp7', name: 'Initial GTR (prior)', type: 'surgery', status: 'completed', startDate: '2024-03-15', endDate: '2024-03-15', protocol: 'Left parietal craniotomy – initial resection', notes: 'Original diagnosis March 2024' },
      { id: 'tp8', name: 'Stupp Protocol (completed)', type: 'chemotherapy', status: 'completed', startDate: '2024-04-10', endDate: '2024-09-15', protocol: 'IMRT 60 Gy/30 fx + TMZ → 6 cycles adjuvant TMZ', cycles: 6, completedCycles: 6, responseAssessment: 'PD at cycle 6', notes: 'Completed all 6 cycles. Recurrence detected on routine MRI.' },
      { id: 'tp9', name: 'Bevacizumab + Lomustine', type: 'chemotherapy', status: 'active', startDate: '2024-10-05', protocol: 'Bevacizumab 10 mg/kg IV q2wk + Lomustine 110 mg q6wk', cycles: 6, completedCycles: 2, notes: 'Second-line therapy. Partial response on interim MRI.' },
    ],
    labResults: [
      { id: 'l13', date: '2024-09-28', category: 'Hematology', testName: 'WBC', value: '9.8', unit: '×10⁹/L', referenceRange: '4.0–11.0', abnormal: false },
      { id: 'l14', date: '2024-09-28', category: 'Hematology', testName: 'Hemoglobin', value: '11.2', unit: 'g/dL', referenceRange: '13.5–17.5', abnormal: true },
      { id: 'l15', date: '2024-09-28', category: 'Chemistry', testName: 'LDH', value: '310', unit: 'U/L', referenceRange: '140–280', abnormal: true },
      { id: 'l16', date: '2024-10-15', category: 'Hematology', testName: 'Platelets', value: '132', unit: '×10⁹/L', referenceRange: '150–400', abnormal: true },
      { id: 'l17', date: '2024-10-15', category: 'Hematology', testName: 'ANC', value: '1.8', unit: '×10⁹/L', referenceRange: '1.5–8.0', abnormal: false },
    ],
    imagingStudies: [
      { id: 'img5', date: '2024-09-28', modality: 'CT Brain', sequences: ['Non-contrast', 'Contrast'], findings: 'New ring-enhancing mass at left parietal resection cavity margin. Surrounding edema. 5 mm midline shift.', impression: 'Recurrent GBM vs radiation necrosis. MRI recommended.', linkedCaseId: 'BraTS2021_00003' },
      { id: 'img6', date: '2024-09-30', modality: 'MRI Brain', sequences: ['T1', 'T1+Gd', 'T2', 'FLAIR', 'DWI', 'DSC Perfusion'], findings: 'Ring-enhancing mass 3.5×3.0×2.8 cm at resection cavity. High rCBV on perfusion. Restricted diffusion at solid component.', impression: 'Recurrent GBM favored over radiation necrosis based on perfusion.', linkedCaseId: 'BraTS2021_00003' },
      { id: 'img7', date: '2024-11-01', modality: 'MRI Brain (interim)', sequences: ['T1+Gd', 'FLAIR'], findings: 'Interval decrease in enhancement (2.8 cm, previously 3.5 cm). Decreased edema.', impression: 'Partial response to Bev+CCNU therapy per RANO criteria.', linkedCaseId: 'BraTS2021_00003' },
    ],
    allergies: [],
    comorbidities: [
      { id: 'c4', condition: 'COPD (mild)', onset: '2019', status: 'controlled', notes: 'Tiotropium inhaler' },
      { id: 'c5', condition: 'Coronary artery disease', onset: '2021', status: 'controlled', notes: 'Stent to LAD 2021. Aspirin, statin.' },
      { id: 'c6', condition: 'Prior DVT (left leg)', onset: '2024-05', status: 'resolved', notes: 'On apixaban for 6 months' },
    ],
    medications: [
      { id: 'm12', name: 'Bevacizumab', dosage: '10 mg/kg', frequency: 'IV q2 weeks', startDate: '2024-10-05', notes: 'Second-line therapy' },
      { id: 'm13', name: 'Lomustine (CCNU)', dosage: '110 mg', frequency: 'PO q6 weeks', startDate: '2024-10-05', notes: 'Second-line with Bev' },
      { id: 'm14', name: 'Dexamethasone', dosage: '8 mg', frequency: 'Daily', startDate: '2024-09-28', notes: 'Cerebral edema' },
      { id: 'm15', name: 'Apixaban', dosage: '5 mg', frequency: 'BID', startDate: '2024-05-15', notes: 'DVT treatment' },
      { id: 'm16', name: 'Aspirin', dosage: '81 mg', frequency: 'Daily', startDate: '2021-11-01', notes: 'CAD post-stent' },
    ],
    visits: [
      { id: 'v9', date: '2024-09-28', department: 'Emergency', doctor: 'Dr. Sun Wei', diagnosis: 'Acute hemiparesis, CT shows recurrence', notes: 'Admitted via ER' },
      { id: 'v10', date: '2024-10-02', department: 'Neuro-oncology', doctor: 'Dr. Chen Li', diagnosis: 'MRI confirmed recurrence, Bev+CCNU started', notes: 'Not candidate for re-resection (eloquent cortex)' },
      { id: 'v11', date: '2024-11-01', department: 'Neuro-oncology', doctor: 'Dr. Chen Li', diagnosis: 'Interim MRI: partial response', notes: 'Continue Bev+CCNU. Monitor blood counts.' },
    ],
    files: [],
  },

  {
    caseId: 'BraTS2021_00005',
    name: 'Li Xiaomei',
    age: 38,
    gender: 'F',
    bloodType: 'AB+',
    phone: '138-0000-0005',
    email: 'lxiaomei@example.com',
    address: '108 Neurology Ward, West China Hospital',
    emergencyContact: 'Li Jun (father) 139-0000-0050',
    admissionDate: '2024-12-01',
    primaryDiagnosis: 'Oligodendroglioma, WHO Grade II, IDH-mutant, 1p/19q co-deleted',
    medicalRecordNumber: 'MRN-2024-00005',
    height: 160,
    weight: 52,
    chiefComplaint: 'New-onset generalized tonic-clonic seizure',
    presentIllness:
      'Ms. Li is a 38-year-old previously healthy female who had a witnessed generalized tonic-clonic seizure at work, lasting ~90 seconds. No prior seizure history. She reports occasional mild headaches and "foggy thinking" over the past 3 months which she attributed to stress. Emergency MRI revealed a left frontal mass.',
    familyHistory: 'Paternal uncle: brain tumor type unspecified, died aged 52. Otherwise unremarkable.',
    socialHistory: 'Non-smoker, non-drinker. Software engineer. Single. Exercises regularly.',
    tumorInfo: {
      location: 'Left frontal lobe (supplementary motor area)',
      laterality: 'left',
      size: '4.0 × 3.5 × 3.0 cm',
      whoGrade: 'II',
      histology: 'Oligodendroglioma, IDH-mutant, 1p/19q co-deleted',
      molecularMarkers: {
        'IDH1': 'R132H Mutant',
        'MGMT Promoter': 'Methylated',
        '1p/19q': 'Co-deleted',
        'ATRX': 'Retained',
        'Ki-67': '5%',
        'TERT Promoter': 'Mutant',
        'CIC': 'Mutant',
        'FUBP1': 'Mutant',
      },
      kps: 95,
    },
    treatmentPlans: [
      { id: 'tp10', name: 'Awake Craniotomy – NTR', type: 'surgery', status: 'completed', startDate: '2024-12-05', endDate: '2024-12-05', protocol: 'Left frontal awake craniotomy with motor mapping', notes: 'Near-total resection. No motor deficits post-op.' },
      { id: 'tp11', name: 'PCV Chemotherapy', type: 'chemotherapy', status: 'active', startDate: '2024-12-20', protocol: 'Procarbazine 60 mg/m² d2–14, CCNU 110 mg/m² d1, Vincristine 1.4 mg/m² d8,29 q8w × 6', cycles: 6, completedCycles: 1, notes: 'Favorable molecular profile. PCV over TMZ per RTOG 9802 long-term data.' },
    ],
    labResults: [
      { id: 'l18', date: '2024-12-01', category: 'Hematology', testName: 'WBC', value: '7.0', unit: '×10⁹/L', referenceRange: '4.0–11.0', abnormal: false },
      { id: 'l19', date: '2024-12-01', category: 'Hematology', testName: 'Hemoglobin', value: '13.2', unit: 'g/dL', referenceRange: '12.0–16.0', abnormal: false },
      { id: 'l20', date: '2024-12-01', category: 'Hematology', testName: 'Platelets', value: '280', unit: '×10⁹/L', referenceRange: '150–400', abnormal: false },
      { id: 'l21', date: '2025-01-10', category: 'Hematology', testName: 'ANC', value: '2.1', unit: '×10⁹/L', referenceRange: '1.5–8.0', abnormal: false },
      { id: 'l22', date: '2025-01-10', category: 'Chemistry', testName: 'AST', value: '42', unit: 'U/L', referenceRange: '10–40', abnormal: true },
    ],
    imagingStudies: [
      { id: 'img8', date: '2024-12-01', modality: 'MRI Brain', sequences: ['T1', 'T1+Gd', 'T2', 'FLAIR', 'DWI', 'MRS'], findings: 'Non-enhancing FLAIR/T2 hyperintense mass in left frontal lobe (4.0×3.5×3.0 cm). No restricted diffusion. Elevated choline/NAA ratio on MRS.', impression: 'Low-grade glioma (WHO II). Surgical resection recommended.', linkedCaseId: 'BraTS2021_00005' },
      { id: 'img9', date: '2024-12-08', modality: 'MRI Brain Post-op', sequences: ['T1+Gd', 'FLAIR'], findings: 'Post-craniotomy changes. Minimal residual FLAIR abnormality at posterior resection margin.', impression: 'Near-total resection achieved.', linkedCaseId: 'BraTS2021_00005' },
    ],
    allergies: [],
    comorbidities: [],
    medications: [
      { id: 'm17', name: 'Levetiracetam', dosage: '750 mg', frequency: 'BID', startDate: '2024-12-02', notes: 'Seizure control' },
      { id: 'm18', name: 'Procarbazine', dosage: '100 mg', frequency: 'Daily d2–14 of q56', startDate: '2024-12-21', notes: 'PCV cycle 1' },
      { id: 'm19', name: 'Lomustine (CCNU)', dosage: '110 mg', frequency: 'Day 1, q8wk', startDate: '2024-12-20', notes: 'PCV cycle 1' },
      { id: 'm20', name: 'Vincristine', dosage: '2 mg', frequency: 'IV days 8 & 29 of cycle', startDate: '2024-12-28', notes: 'PCV cycle 1' },
    ],
    visits: [
      { id: 'v12', date: '2024-12-01', department: 'Neurology', doctor: 'Dr. Huang Wei', diagnosis: 'New-onset seizure, MRI: left frontal mass', notes: 'Transferred to neurosurgery' },
      { id: 'v13', date: '2024-12-05', department: 'Neurosurgery', doctor: 'Dr. Ma Dong', diagnosis: 'Awake craniotomy – NTR', notes: 'No motor deficits. Quick recovery.' },
      { id: 'v14', date: '2024-12-15', department: 'Neuro-oncology', doctor: 'Dr. Xu Fang', diagnosis: 'Oligodendroglioma WHO II, 1p/19q co-del', notes: 'Excellent prognosis. Started PCV per RTOG 9802.' },
    ],
    files: [],
  },

  {
    caseId: 'BraTS2021_00006',
    name: 'Robert Johnson',
    age: 57,
    gender: 'M',
    bloodType: 'O-',
    phone: '138-0000-0006',
    email: 'rjohnson@example.com',
    address: '320 Neuro Ward, Xuanwu Hospital',
    emergencyContact: 'Mary Johnson (wife) 139-0000-0060',
    admissionDate: '2024-08-20',
    primaryDiagnosis: 'Meningioma, WHO Grade II (atypical)',
    medicalRecordNumber: 'MRN-2024-00006',
    height: 180,
    weight: 88,
    chiefComplaint: 'Progressive headache and personality/behavioral changes for 6 weeks',
    presentIllness:
      'Mr. Johnson is a 57-year-old male with 6 weeks of worsening headaches, most marked in the morning. His wife reports irritability, apathy, and uncharacteristic aggression. He also notes bilateral leg weakness on walking and one episode of urinary incontinence. Examination revealed bilateral papilledema and mild lower extremity weakness.',
    familyHistory: 'No family history of brain tumors. Father: MI at 62. Mother: hypertension.',
    socialHistory: 'Non-smoker. Moderate alcohol (2–3 beers/week). Construction supervisor. Married 30 years.',
    tumorInfo: {
      location: 'Parasagittal (bilateral frontal, superior sagittal sinus involvement)',
      laterality: 'bilateral',
      size: '5.8 × 4.5 × 4.2 cm',
      whoGrade: 'II',
      histology: 'Atypical meningioma (increased mitotic activity, brain invasion)',
      molecularMarkers: {
        'NF2': 'Loss of function',
        'Ki-67': '12%',
        'Progesterone Receptor': 'Negative',
        'EMA': 'Positive',
        'SSTR2A': 'Positive',
      },
      kps: 85,
    },
    treatmentPlans: [
      { id: 'tp12', name: 'Craniotomy – Simpson Gr II', type: 'surgery', status: 'completed', startDate: '2024-08-25', endDate: '2024-08-25', protocol: 'Bifrontal craniotomy, Simpson Grade II resection (dural attachment coagulated)', notes: 'Could not resect sinus-invading portion. Brain invasion confirmed on histology.' },
      { id: 'tp13', name: 'Adjuvant Fractionated RT', type: 'radiation', status: 'active', startDate: '2024-10-01', endDate: '2024-11-12', protocol: 'Fractionated EBRT 54 Gy / 30 fractions to tumor bed + residual', notes: 'Fraction 20 of 30. Tolerating well. Fatigue reported.' },
    ],
    labResults: [
      { id: 'l23', date: '2024-08-20', category: 'Hematology', testName: 'WBC', value: '8.4', unit: '×10⁹/L', referenceRange: '4.0–11.0', abnormal: false },
      { id: 'l24', date: '2024-08-20', category: 'Hematology', testName: 'Hemoglobin', value: '15.0', unit: 'g/dL', referenceRange: '13.5–17.5', abnormal: false },
      { id: 'l25', date: '2024-08-20', category: 'Coagulation', testName: 'INR', value: '1.0', unit: '', referenceRange: '0.9–1.1', abnormal: false },
      { id: 'l26', date: '2024-08-20', category: 'Chemistry', testName: 'Sodium', value: '141', unit: 'mEq/L', referenceRange: '136–145', abnormal: false },
    ],
    imagingStudies: [
      { id: 'img10', date: '2024-08-20', modality: 'MRI Brain', sequences: ['T1', 'T1+Gd', 'T2', 'FLAIR'], findings: 'Large homogeneously enhancing extra-axial mass in the parasagittal region (5.8×4.5×4.2 cm) with broad dural base. Invades superior sagittal sinus posteriorly. Bilateral frontal edema.', impression: 'Large atypical meningioma with sinus invasion. Surgical resection recommended.', linkedCaseId: 'BraTS2021_00006' },
      { id: 'img11', date: '2024-09-01', modality: 'MRI Brain Post-op', sequences: ['T1+Gd', 'FLAIR'], findings: 'Post-op changes. Small residual enhancement at sinus junction. Decreased edema.', impression: 'Simpson Grade II resection. Residual at sinus. Adjuvant RT recommended.', linkedCaseId: 'BraTS2021_00006' },
    ],
    allergies: [
      { id: 'a3', allergen: 'Iodinated contrast', reaction: 'Nausea, mild urticaria', severity: 'mild' },
    ],
    comorbidities: [
      { id: 'c7', condition: 'Hypertension', onset: '2016', status: 'controlled', notes: 'Lisinopril 10 mg daily' },
      { id: 'c8', condition: 'Hyperlipidemia', onset: '2018', status: 'controlled', notes: 'Atorvastatin 20 mg daily' },
    ],
    medications: [
      { id: 'm21', name: 'Phenytoin', dosage: '300 mg', frequency: 'Daily', startDate: '2024-08-21', notes: 'Peri-operative seizure prophylaxis' },
      { id: 'm22', name: 'Lisinopril', dosage: '10 mg', frequency: 'Daily', startDate: '2016-03-01', notes: 'Hypertension' },
      { id: 'm23', name: 'Atorvastatin', dosage: '20 mg', frequency: 'Daily', startDate: '2018-07-01', notes: 'Hyperlipidemia' },
      { id: 'm24', name: 'Omeprazole', dosage: '20 mg', frequency: 'Daily', startDate: '2024-08-21', notes: 'GI protection' },
    ],
    visits: [
      { id: 'v15', date: '2024-08-20', department: 'Neurosurgery', doctor: 'Dr. Zhang Li', diagnosis: 'Large parasagittal meningioma w/ sinus invasion', notes: 'Admitted for surgery' },
      { id: 'v16', date: '2024-08-25', department: 'Neurosurgery', doctor: 'Dr. Zhang Li', diagnosis: 'Simpson Gr II resection; path: atypical meningioma', notes: 'Brain invasion confirmed. Adjuvant RT planned.' },
      { id: 'v17', date: '2024-10-01', department: 'Radiation Oncology', doctor: 'Dr. He Wei', diagnosis: 'Started adjuvant fractionated RT', notes: '54 Gy / 30 fractions to tumor bed' },
    ],
    files: [],
  },

  {
    caseId: 'BraTS2021_00008',
    name: 'Chen Yun',
    age: 41,
    gender: 'F',
    bloodType: 'A-',
    phone: '138-0000-0008',
    email: 'chenyun@example.com',
    address: '215 Radiation Oncology, Zhongshan Hospital',
    emergencyContact: 'Wang Tao (husband) 139-0000-0080',
    admissionDate: '2024-11-18',
    primaryDiagnosis: 'Diffuse Astrocytoma, WHO Grade II, IDH-mutant',
    medicalRecordNumber: 'MRN-2024-00008',
    height: 165,
    weight: 55,
    chiefComplaint: 'Incidental finding of brain mass on MRI for chronic migraine evaluation',
    presentIllness:
      'Ms. Chen is a 41-year-old female with longstanding migraines who had an MRI performed for worsening headache pattern. MRI incidentally revealed a right insular mass. She denies seizures, weakness, numbness, speech difficulty, or vision changes. Neurological examination is entirely normal. Her migraines are otherwise well-controlled on topiramate.',
    familyHistory: 'Mother: breast cancer at 62, alive. No neuro-oncology family history.',
    socialHistory: 'Non-smoker. Occasional wine. University professor (literature). Married. Two children ages 10 and 13.',
    tumorInfo: {
      location: 'Right insular cortex',
      laterality: 'right',
      size: '3.2 × 2.8 × 2.5 cm',
      whoGrade: 'II',
      histology: 'Diffuse Astrocytoma, IDH-mutant',
      molecularMarkers: {
        'IDH1': 'R132H Mutant',
        'MGMT Promoter': 'Methylated',
        '1p/19q': 'Intact',
        'ATRX': 'Lost',
        'p53': 'Mutant (~45%)',
        'Ki-67': '4%',
        'TERT Promoter': 'Wildtype',
      },
      kps: 100,
    },
    treatmentPlans: [
      { id: 'tp14', name: 'Stereotactic Biopsy', type: 'surgery', status: 'completed', startDate: '2024-11-20', endDate: '2024-11-20', protocol: 'Frame-based stereotactic biopsy of right insular lesion', notes: 'Diagnostic only (insular location precludes safe resection). Pathology confirmed DA II.' },
      { id: 'tp15', name: 'Concurrent Chemoradiation', type: 'radiation', status: 'active', startDate: '2024-12-02', protocol: 'IMRT 54 Gy / 30 fx + concurrent TMZ 75 mg/m²/day', notes: 'Started 12 days after biopsy. Week 2. Tolerating well.' },
      { id: 'tp16', name: 'Adjuvant TMZ', type: 'chemotherapy', status: 'planned', startDate: '2025-01-20', protocol: 'TMZ 150-200 mg/m², 5/28 days × 6–12 cycles', cycles: 12, completedCycles: 0, notes: 'Extended adjuvant TMZ for IDH-mutant astrocytoma' },
    ],
    labResults: [
      { id: 'l27', date: '2024-11-18', category: 'Hematology', testName: 'WBC', value: '5.9', unit: '×10⁹/L', referenceRange: '4.0–11.0', abnormal: false },
      { id: 'l28', date: '2024-11-18', category: 'Hematology', testName: 'Hemoglobin', value: '13.5', unit: 'g/dL', referenceRange: '12.0–16.0', abnormal: false },
      { id: 'l29', date: '2024-11-18', category: 'Hematology', testName: 'Platelets', value: '222', unit: '×10⁹/L', referenceRange: '150–400', abnormal: false },
      { id: 'l30', date: '2024-12-10', category: 'Hematology', testName: 'ANC', value: '3.5', unit: '×10⁹/L', referenceRange: '1.5–8.0', abnormal: false },
    ],
    imagingStudies: [
      { id: 'img12', date: '2024-11-18', modality: 'MRI Brain', sequences: ['T1', 'T1+Gd', 'T2', 'FLAIR', 'DWI', 'SWI'], findings: 'FLAIR/T2 hyperintense non-enhancing mass in right insular cortex (3.2×2.8×2.5 cm). No restricted diffusion. No mass effect.', impression: 'Low-grade glioma of right insula. Recommend stereotactic biopsy.', linkedCaseId: 'BraTS2021_00008' },
      { id: 'img13', date: '2024-11-22', modality: 'MRI Brain (post-biopsy)', sequences: ['T1+Gd', 'FLAIR'], findings: 'Expected post-biopsy changes. Small tract hemorrhage resolving. Mass unchanged.', impression: 'Expected post-biopsy appearance. No complication.', linkedCaseId: 'BraTS2021_00008' },
    ],
    allergies: [
      { id: 'a4', allergen: 'Aspirin', reaction: 'Bronchospasm', severity: 'moderate' },
    ],
    comorbidities: [
      { id: 'c9', condition: 'Chronic migraine with aura', onset: '2010', status: 'controlled', notes: 'Topiramate 100 mg + sumatriptan PRN' },
      { id: 'c10', condition: 'Generalized anxiety disorder', onset: '2018', status: 'active', notes: 'Sertraline 50 mg daily' },
    ],
    medications: [
      { id: 'm25', name: 'Temozolomide', dosage: '75 mg/m²', frequency: 'Daily during RT', startDate: '2024-12-02', notes: 'Concurrent chemoradiation' },
      { id: 'm26', name: 'TMP-SMX DS', dosage: '1 tablet', frequency: 'MWF', startDate: '2024-12-02', notes: 'PJP prophylaxis' },
      { id: 'm27', name: 'Topiramate', dosage: '100 mg', frequency: 'Daily', startDate: '2010-05-01', notes: 'Migraine prophylaxis' },
      { id: 'm28', name: 'Sertraline', dosage: '50 mg', frequency: 'Daily', startDate: '2018-09-01', notes: 'GAD' },
    ],
    visits: [
      { id: 'v18', date: '2024-11-18', department: 'Neuro-oncology', doctor: 'Dr. Lin Jing', diagnosis: 'Incidental right insular mass on migraine MRI', notes: 'Biopsy planned' },
      { id: 'v19', date: '2024-11-20', department: 'Neurosurgery', doctor: 'Dr. Qian Feng', diagnosis: 'Stereotactic biopsy performed', notes: 'DA II, IDH-mutant. No complications.' },
      { id: 'v20', date: '2024-12-02', department: 'Radiation Oncology', doctor: 'Dr. Yang Bo', diagnosis: 'Started IMRT + concurrent TMZ', notes: '54 Gy/30 fx. MGMT methylated.' },
    ],
    files: [],
  },

  {
    caseId: 'BraTS2021_00009',
    name: 'Ahmed Hassan',
    age: 49,
    gender: 'M',
    bloodType: 'B-',
    phone: '138-0000-0009',
    email: 'ahassan@example.com',
    address: '505 Oncology Unit, Changhai Hospital',
    emergencyContact: 'Fatima Hassan (wife) 139-0000-0090',
    admissionDate: '2024-10-08',
    primaryDiagnosis: 'Glioblastoma multiforme, MGMT unmethylated, IDH-wildtype',
    medicalRecordNumber: 'MRN-2024-00009',
    height: 175,
    weight: 95,
    chiefComplaint: 'Progressive cognitive decline, behavioral changes, and gait unsteadiness for 4 weeks',
    presentIllness:
      'Mr. Hassan is a 49-year-old male presenting with 4 weeks of progressive memory difficulties, executive dysfunction, and gait unsteadiness. His wife reports significant personality changes: increased irritability, poor judgment, and social withdrawal. He has had one fall at work. MRI done by his PCP revealed a large right parietal mass.',
    familyHistory: 'Father: type 2 diabetes, alive. Mother: hypertension, alive. No family history of cancer.',
    socialHistory: 'Non-smoker. No alcohol (religious). Electrical engineer. Married with 3 children. Sedentary lifestyle. BMI 31.',
    tumorInfo: {
      location: 'Right parietal lobe with extension to corpus callosum',
      laterality: 'right',
      size: '4.8 × 4.2 × 3.6 cm',
      whoGrade: 'IV',
      histology: 'Glioblastoma, IDH-wildtype',
      molecularMarkers: {
        'IDH1/2': 'Wildtype',
        'MGMT Promoter': 'Unmethylated',
        '1p/19q': 'Intact',
        'EGFR': 'Amplified',
        'Ki-67': '30%',
        'TERT Promoter': 'Mutant',
        'PTEN': 'Normal',
        'CDKN2A': 'Intact',
      },
      kps: 70,
    },
    treatmentPlans: [
      { id: 'tp17', name: 'Subtotal Resection', type: 'surgery', status: 'completed', startDate: '2024-10-12', endDate: '2024-10-12', protocol: 'Right parietal craniotomy, subtotal resection (STR)', notes: 'Limited by corpus callosum involvement. ~80% debulking. Post-op: improved gait, KPS 70→75.' },
      { id: 'tp18', name: 'Standard RT + TMZ', type: 'radiation', status: 'completed', startDate: '2024-10-28', endDate: '2024-12-08', protocol: 'IMRT 60 Gy / 30 fx + concurrent TMZ 75 mg/m²/day', completedCycles: 1, notes: 'Completed concurrent phase. MGMT unmethylated but TMZ still part of standard Stupp.' },
      { id: 'tp19', name: 'Adjuvant TMZ + TTFields', type: 'chemotherapy', status: 'active', startDate: '2025-01-06', protocol: 'TMZ 200 mg/m² 5/28 days × 6 cycles + Optune TTFields device', cycles: 6, completedCycles: 0, notes: 'TTFields approved. Device fitting scheduled. MGMT unmethylated – consider clinical trial if PD.' },
    ],
    labResults: [
      { id: 'l31', date: '2024-10-08', category: 'Hematology', testName: 'WBC', value: '8.1', unit: '×10⁹/L', referenceRange: '4.0–11.0', abnormal: false },
      { id: 'l32', date: '2024-10-08', category: 'Chemistry', testName: 'HbA1c', value: '7.2', unit: '%', referenceRange: '<5.7', abnormal: true },
      { id: 'l33', date: '2024-10-08', category: 'Chemistry', testName: 'Fasting glucose', value: '145', unit: 'mg/dL', referenceRange: '70–100', abnormal: true },
      { id: 'l34', date: '2024-10-08', category: 'Chemistry', testName: 'Total cholesterol', value: '238', unit: 'mg/dL', referenceRange: '<200', abnormal: true },
      { id: 'l35', date: '2024-12-10', category: 'Hematology', testName: 'ANC', value: '1.6', unit: '×10⁹/L', referenceRange: '1.5–8.0', abnormal: false },
    ],
    imagingStudies: [
      { id: 'img14', date: '2024-10-08', modality: 'MRI Brain', sequences: ['T1', 'T1+Gd', 'T2', 'FLAIR', 'DWI', 'DSC Perfusion'], findings: 'Large heterogeneously enhancing mass in right parietal lobe (4.8×4.2×3.6 cm) crossing midline through corpus callosum. Central necrosis. High rCBV. Surrounding edema.', impression: 'High-grade glioma (GBM) with callosal extension ("butterfly" pattern).', linkedCaseId: 'BraTS2021_00009' },
      { id: 'img15', date: '2024-10-15', modality: 'MRI Brain Post-op', sequences: ['T1+Gd', 'FLAIR'], findings: 'Subtotal resection cavity. Residual enhancement at corpus callosum crossing. Reduced mass effect.', impression: 'Subtotal resection (~80%). Residual disease at midline crossing.', linkedCaseId: 'BraTS2021_00009' },
    ],
    allergies: [],
    comorbidities: [
      { id: 'c11', condition: 'Type 2 diabetes mellitus', onset: '2019', status: 'active', notes: 'Metformin 1000 mg BID. Suboptimal control w/ steroids.' },
      { id: 'c12', condition: 'Obesity (BMI 31)', onset: '2015', status: 'active', notes: 'Counseled on weight management' },
      { id: 'c13', condition: 'Hyperlipidemia', onset: '2020', status: 'controlled', notes: 'Rosuvastatin 10 mg daily' },
    ],
    medications: [
      { id: 'm29', name: 'Temozolomide', dosage: '200 mg/m²', frequency: '5/28 days', startDate: '2025-01-06', notes: 'Adjuvant phase cycle 1' },
      { id: 'm30', name: 'Dexamethasone', dosage: '2 mg', frequency: 'BID', startDate: '2024-10-08', endDate: '2024-11-01', notes: 'Tapered off' },
      { id: 'm31', name: 'Metformin', dosage: '1000 mg', frequency: 'BID', startDate: '2019-04-01', notes: 'DM control' },
      { id: 'm32', name: 'Rosuvastatin', dosage: '10 mg', frequency: 'Daily', startDate: '2020-06-01', notes: 'Hyperlipidemia' },
      { id: 'm33', name: 'Pantoprazole', dosage: '40 mg', frequency: 'Daily', startDate: '2024-10-08', notes: 'GI protection w/ dex' },
    ],
    visits: [
      { id: 'v21', date: '2024-10-08', department: 'Neurosurgery', doctor: 'Dr. Qian Feng', diagnosis: 'Right parietal GBM with callosal extension', notes: 'STR planned due to midline involvement' },
      { id: 'v22', date: '2024-10-12', department: 'Neurosurgery', doctor: 'Dr. Qian Feng', diagnosis: 'Post-STR day 0', notes: '80% debulking. Improved cognition.' },
      { id: 'v23', date: '2024-10-28', department: 'Radiation Oncology', doctor: 'Dr. He Wei', diagnosis: 'Started RT + TMZ', notes: 'Standard Stupp despite MGMT unmethylated.' },
      { id: 'v24', date: '2024-12-15', department: 'Neuro-oncology', doctor: 'Dr. Wu Ming', diagnosis: 'Completed concurrent phase', notes: 'TTFields discussed and approved. Device fitting next visit.' },
    ],
    files: [],
  },

  {
    caseId: 'BraTS2021_00011',
    name: 'Anna Kowalski',
    age: 35,
    gender: 'F',
    bloodType: 'A+',
    phone: '138-0000-0011',
    email: 'akowalski@example.com',
    address: '103 Neuro Ward, Ruijin Hospital',
    emergencyContact: 'Piotr Kowalski (husband) 139-0000-0110',
    admissionDate: '2024-12-10',
    primaryDiagnosis: 'Pilocytic Astrocytoma, WHO Grade I',
    medicalRecordNumber: 'MRN-2024-00011',
    height: 168,
    weight: 62,
    chiefComplaint: 'Progressive gait unsteadiness, nausea, and headache for 6 weeks',
    presentIllness:
      'Ms. Kowalski is a 35-year-old previously healthy female with 6 weeks of progressive ataxia (difficulty walking, bumping into doorframes), morning nausea, and occipital headaches. Over the last week, she developed intermittent diplopia on leftward gaze. No seizures, no weakness, no speech difficulty. Examination shows truncal and appendicular ataxia, left VI nerve paresis, and mild papilledema.',
    familyHistory: 'No significant family history. Both parents healthy.',
    socialHistory: 'Non-smoker. Social alcohol. Veterinarian. Married. Expecting first child (pregnancy test negative at admission).',
    tumorInfo: {
      location: 'Cerebellar vermis with extension to left hemisphere',
      laterality: 'midline/left',
      size: '3.0 × 2.5 × 2.2 cm',
      whoGrade: 'I',
      histology: 'Pilocytic Astrocytoma',
      molecularMarkers: {
        'BRAF': 'KIAA1549-BRAF fusion (FISH+)',
        'IDH1/2': 'Wildtype',
        'Ki-67': '2%',
        'p53': 'Wildtype',
        'ATRX': 'Retained',
      },
      kps: 90,
    },
    treatmentPlans: [
      { id: 'tp20', name: 'Suboccipital Craniotomy – GTR', type: 'surgery', status: 'completed', startDate: '2024-12-12', endDate: '2024-12-12', protocol: 'Midline suboccipital craniotomy with microsurgical gross total resection', notes: 'Well-circumscribed tumor, GTR confirmed on post-op MRI. No CSF leak.' },
      { id: 'tp21', name: 'Surveillance Only', type: 'observation', status: 'active', startDate: '2024-12-20', protocol: 'MRI surveillance q6 months × 5 years, then annually', notes: 'WHO Grade I with GTR – excellent prognosis. >95% 10-year PFS. No adjuvant therapy needed.' },
    ],
    labResults: [
      { id: 'l36', date: '2024-12-10', category: 'Hematology', testName: 'WBC', value: '6.8', unit: '×10⁹/L', referenceRange: '4.0–11.0', abnormal: false },
      { id: 'l37', date: '2024-12-10', category: 'Hematology', testName: 'Hemoglobin', value: '13.0', unit: 'g/dL', referenceRange: '12.0–16.0', abnormal: false },
      { id: 'l38', date: '2024-12-10', category: 'Chemistry', testName: 'Creatinine', value: '0.7', unit: 'mg/dL', referenceRange: '0.5–1.1', abnormal: false },
      { id: 'l39', date: '2024-12-10', category: 'Endocrine', testName: 'β-hCG', value: '<1', unit: 'mIU/mL', referenceRange: '<5', abnormal: false },
    ],
    imagingStudies: [
      { id: 'img16', date: '2024-12-10', modality: 'MRI Brain', sequences: ['T1', 'T1+Gd', 'T2', 'FLAIR', 'DWI'], findings: 'Well-circumscribed cystic mass with enhancing mural nodule in cerebellar vermis (3.0×2.5×2.2 cm). Mild 4th ventricle compression. No hydrocephalus.', impression: 'Classic pilocytic astrocytoma appearance. Surgical excision recommended.', linkedCaseId: 'BraTS2021_00011' },
      { id: 'img17', date: '2024-12-14', modality: 'MRI Brain Post-op', sequences: ['T1+Gd', 'FLAIR', 'DWI'], findings: 'Post-craniotomy changes. No residual enhancing tumor or cystic component. 4th ventricle decompressed.', impression: 'Gross total resection confirmed. No residual tumor. Decompressed posterior fossa.', linkedCaseId: 'BraTS2021_00011' },
    ],
    allergies: [],
    comorbidities: [],
    medications: [
      { id: 'm34', name: 'Acetaminophen', dosage: '500 mg', frequency: 'PRN q6h', startDate: '2024-12-12', notes: 'Post-op pain' },
      { id: 'm35', name: 'Ondansetron', dosage: '4 mg', frequency: 'PRN', startDate: '2024-12-12', notes: 'Post-op nausea' },
    ],
    visits: [
      { id: 'v25', date: '2024-12-10', department: 'Neurosurgery', doctor: 'Dr. Gao Shan', diagnosis: 'Cerebellar mass – pilocytic astrocytoma suspected', notes: 'Admitted for surgical excision' },
      { id: 'v26', date: '2024-12-12', department: 'Neurosurgery', doctor: 'Dr. Gao Shan', diagnosis: 'Suboccipital craniotomy – GTR', notes: 'Complete excision. Ataxia improving post-op.' },
      { id: 'v27', date: '2024-12-15', department: 'Neurosurgery', doctor: 'Dr. Gao Shan', diagnosis: 'Post-op MRI: no residual', notes: 'Discharge planned. Follow-up MRI in 3 months.' },
    ],
    files: [],
  },

  {
    caseId: 'BraTS2021_00012',
    name: 'David Kim',
    age: 60,
    gender: 'M',
    bloodType: 'AB-',
    phone: '138-0000-0012',
    email: 'dkim@example.com',
    address: '410 Oncology Ward, Sun Yat-sen Memorial',
    emergencyContact: 'Jiyoung Kim (wife) 139-0000-0120',
    admissionDate: '2024-09-12',
    primaryDiagnosis: 'Brain metastases from NSCLC (lung adenocarcinoma, EGFR T790M+)',
    medicalRecordNumber: 'MRN-2024-00012',
    height: 170,
    weight: 65,
    chiefComplaint: 'First-time seizure at home followed by right arm weakness',
    presentIllness:
      'Mr. Kim is a 60-year-old male with known stage IV NSCLC (EGFR L858R → T790M mutation, diagnosed 2023) who had a seizure at home (witnessed by wife, ~1 min GTC). Post-ictally he noted persistent right arm weakness and mild headache. He was on erlotinib as first-line therapy. Staging MRI brain revealed multiple brain metastases.',
    familyHistory: 'Father: lung cancer at 70 (smoker). Mother: diabetes. Brother: healthy.',
    socialHistory: 'Former smoker (30 pack-years, quit 2010). No alcohol. Retired taxi driver. Married.',
    tumorInfo: {
      location: 'Multiple: left frontal (2.1 cm), right parietal (1.5 cm), left cerebellar (1.2 cm)',
      laterality: 'bilateral',
      size: '2.1 cm (largest), 3 lesions total',
      whoGrade: 'N/A (metastatic)',
      histology: 'Metastatic adenocarcinoma (lung primary), EGFR T790M+',
      molecularMarkers: {
        'EGFR': 'L858R + T790M (dual mutation)',
        'ALK': 'Negative',
        'ROS1': 'Negative',
        'PD-L1 TPS': '60%',
        'KRAS': 'Wildtype',
        'MET': 'Not amplified',
        'Ki-67': '25% (brain met biopsy)',
      },
      kps: 75,
    },
    treatmentPlans: [
      { id: 'tp22', name: 'SRS to 3 Brain Lesions', type: 'radiation', status: 'completed', startDate: '2024-09-18', endDate: '2024-09-18', protocol: 'Gamma Knife SRS: 20 Gy to left frontal, 22 Gy to right parietal, 22 Gy to left cerebellar', notes: 'Single-fraction SRS. All 3 lesions treated. Well-tolerated.' },
      { id: 'tp23', name: 'Osimertinib (3rd-gen TKI)', type: 'targeted', status: 'active', startDate: '2024-09-15', protocol: 'Osimertinib 80 mg PO daily (switched from erlotinib due to T790M)', notes: 'Good systemic and CNS response at 3-month restaging. Brain-penetrant TKI.' },
      { id: 'tp24', name: 'Surveillance Imaging', type: 'observation', status: 'active', startDate: '2024-10-15', protocol: 'Brain MRI q3 months, chest/abd CT q3 months', notes: 'Monitoring for CNS and systemic response/progression' },
    ],
    labResults: [
      { id: 'l40', date: '2024-09-12', category: 'Hematology', testName: 'WBC', value: '6.2', unit: '×10⁹/L', referenceRange: '4.0–11.0', abnormal: false },
      { id: 'l41', date: '2024-09-12', category: 'Hematology', testName: 'Hemoglobin', value: '12.5', unit: 'g/dL', referenceRange: '13.5–17.5', abnormal: true },
      { id: 'l42', date: '2024-09-12', category: 'Tumor Markers', testName: 'CEA', value: '12.3', unit: 'ng/mL', referenceRange: '<5.0', abnormal: true },
      { id: 'l43', date: '2024-09-12', category: 'Chemistry', testName: 'LDH', value: '285', unit: 'U/L', referenceRange: '140–280', abnormal: true },
      { id: 'l44', date: '2024-12-12', category: 'Tumor Markers', testName: 'CEA', value: '5.8', unit: 'ng/mL', referenceRange: '<5.0', abnormal: true },
    ],
    imagingStudies: [
      { id: 'img18', date: '2024-09-12', modality: 'MRI Brain', sequences: ['T1', 'T1+Gd', 'T2', 'FLAIR', 'DWI'], findings: 'Three enhancing lesions: left frontal 2.1 cm, right parietal 1.5 cm, left cerebellar 1.2 cm. Surrounding edema. No leptomeningeal disease.', impression: 'Multiple brain metastases from known NSCLC. SRS recommended for limited number of lesions.', linkedCaseId: 'BraTS2021_00012' },
      { id: 'img19', date: '2024-12-15', modality: 'MRI Brain (3-mo follow-up)', sequences: ['T1+Gd', 'FLAIR', 'DWI'], findings: 'All 3 lesions decreased in size. Left frontal: 0.8 cm (was 2.1). Right parietal: 0.5 cm. Left cerebellar: barely visible. Decreased edema.', impression: 'Excellent response to SRS + osimertinib. Partial response by RANO-BM.', linkedCaseId: 'BraTS2021_00012' },
      { id: 'img20', date: '2024-12-15', modality: 'CT Chest/Abdomen', findings: 'Primary lung mass in right upper lobe decreased from 3.5 cm → 1.2 cm. No new systemic metastases. Stable adrenal nodules.', impression: 'Partial response systemically on osimertinib per RECIST 1.1.' },
    ],
    allergies: [
      { id: 'a5', allergen: 'Codeine', reaction: 'Severe nausea/vomiting', severity: 'moderate' },
    ],
    comorbidities: [
      { id: 'c14', condition: 'COPD (moderate)', onset: '2018', status: 'controlled', notes: 'Tiotropium + albuterol PRN. FEV1 65%.' },
      { id: 'c15', condition: 'Former smoker', onset: '1980', status: 'resolved', notes: '30 pack-years, quit 2010' },
    ],
    medications: [
      { id: 'm36', name: 'Osimertinib', dosage: '80 mg', frequency: 'Daily', startDate: '2024-09-15', notes: 'EGFR T790M targeted therapy (CNS-penetrant)' },
      { id: 'm37', name: 'Levetiracetam', dosage: '500 mg', frequency: 'BID', startDate: '2024-09-13', notes: 'Seizure prophylaxis' },
      { id: 'm38', name: 'Dexamethasone', dosage: '4 mg', frequency: 'Daily (tapering)', startDate: '2024-09-12', endDate: '2024-10-01', notes: 'Brain mets edema, tapered' },
      { id: 'm39', name: 'Tiotropium', dosage: '18 mcg', frequency: 'Inhaled daily', startDate: '2018-03-01', notes: 'COPD maintenance' },
    ],
    visits: [
      { id: 'v28', date: '2024-09-12', department: 'Neurology', doctor: 'Dr. Ren Bo', diagnosis: 'New seizure, MRI: 3 brain mets', notes: 'Known NSCLC EGFR+. Brain staging new.' },
      { id: 'v29', date: '2024-09-15', department: 'Medical Oncology', doctor: 'Dr. Liang Hua', diagnosis: 'Switched erlotinib → osimertinib', notes: 'T790M resistance mutation. Osimertinib has CNS activity.' },
      { id: 'v30', date: '2024-09-18', department: 'Radiation Oncology', doctor: 'Dr. He Wei', diagnosis: 'SRS to 3 brain mets', notes: 'Gamma Knife single fraction. Well tolerated.' },
      { id: 'v31', date: '2024-12-15', department: 'Neuro-oncology', doctor: 'Dr. Wu Ming', diagnosis: '3-mo F/U: excellent CNS response', notes: 'All lesions shrinking. CEA trending down. Continue osimertinib.' },
    ],
    files: [],
  },

  {
    caseId: 'BraTS2021_00014',
    name: 'Sophie Martin',
    age: 28,
    gender: 'F',
    bloodType: 'O+',
    phone: '138-0000-0014',
    email: 'smartin@example.com',
    address: '220 Neuro ICU, Tongji Hospital',
    emergencyContact: 'Pierre Martin (father) 139-0000-0140',
    admissionDate: '2024-11-22',
    primaryDiagnosis: 'Ependymoma, WHO Grade II, posterior fossa',
    medicalRecordNumber: 'MRN-2024-00014',
    height: 170,
    weight: 58,
    chiefComplaint: 'Severe occipital headache, recurrent vomiting, and double vision for 2 weeks',
    presentIllness:
      'Ms. Martin is a 28-year-old female presenting with 2 weeks of progressively severe occipital headaches, worst in the morning, associated with projectile vomiting (6–8 episodes/day). She developed diplopia on horizontal gaze 5 days ago and noted gait unsteadiness. She was referred emergently from her local hospital after CT showed a posterior fossa mass with obstructive hydrocephalus. On arrival, GCS 14 (E4V4M6), bilateral VI nerve palsies, truncal ataxia, and papilledema.',
    familyHistory: 'No relevant family history. Parents both healthy.',
    socialHistory: 'Non-smoker. Social alcohol. Graduate student (neuroscience – ironic). Single. Active runner (marathons).',
    tumorInfo: {
      location: '4th ventricle / posterior fossa (floor of 4th ventricle)',
      laterality: 'midline',
      size: '3.5 × 3.0 × 2.8 cm',
      whoGrade: 'II',
      histology: 'Ependymoma, classic (WHO II)',
      molecularMarkers: {
        'RELA Fusion': 'Negative',
        'YAP1 Fusion': 'Negative',
        'H3K27me3': 'Retained (Group A/PFA excluded)',
        'Ki-67': '8%',
        'EMA': 'Positive (dot-like)',
        'GFAP': 'Positive',
        'Methylation Class': 'PFB (subgroup B)',
      },
      kps: 70,
    },
    treatmentPlans: [
      { id: 'tp25', name: 'EVD Placement', type: 'surgery', status: 'completed', startDate: '2024-11-22', endDate: '2024-11-22', protocol: 'Emergency right frontal EVD for acute hydrocephalus', notes: 'ICP was 32 cmH₂O. Immediate improvement after drainage. GCS 15.' },
      { id: 'tp26', name: 'Suboccipital Craniotomy – GTR', type: 'surgery', status: 'completed', startDate: '2024-11-24', endDate: '2024-11-24', protocol: 'Midline suboccipital craniotomy, microsurgical GTR of 4th ventricular ependymoma', notes: 'Tumor arose from floor of 4th ventricle. GTR achieved with brainstem monitoring. EVD weaned and removed post-op day 3.' },
      { id: 'tp27', name: 'Adjuvant Conformal RT', type: 'radiation', status: 'planned', startDate: '2025-01-10', protocol: 'Conformal RT 54 Gy / 30 fractions to posterior fossa', notes: 'No chemotherapy for WHO II ependymoma. RT per CERN protocol.' },
    ],
    labResults: [
      { id: 'l45', date: '2024-11-22', category: 'Hematology', testName: 'WBC', value: '9.1', unit: '×10⁹/L', referenceRange: '4.0–11.0', abnormal: false },
      { id: 'l46', date: '2024-11-22', category: 'Hematology', testName: 'Hemoglobin', value: '14.0', unit: 'g/dL', referenceRange: '12.0–16.0', abnormal: false },
      { id: 'l47', date: '2024-11-22', category: 'Hematology', testName: 'Platelets', value: '310', unit: '×10⁹/L', referenceRange: '150–400', abnormal: false },
      { id: 'l48', date: '2024-11-22', category: 'Chemistry', testName: 'Sodium', value: '138', unit: 'mEq/L', referenceRange: '136–145', abnormal: false },
      { id: 'l49', date: '2024-11-25', category: 'CSF Analysis', testName: 'CSF Cytology', value: 'Negative for malignant cells', unit: '', referenceRange: 'Negative', abnormal: false },
    ],
    imagingStudies: [
      { id: 'img21', date: '2024-11-22', modality: 'CT Brain (Emergency)', findings: 'Posterior fossa mass occupying the 4th ventricle. Triventricular hydrocephalus. No calcification.', impression: 'Posterior fossa mass with obstructive hydrocephalus. Urgent EVD + MRI.' },
      { id: 'img22', date: '2024-11-23', modality: 'MRI Brain', sequences: ['T1', 'T1+Gd', 'T2', 'FLAIR', 'DWI'], findings: 'Well-demarcated, heterogeneously enhancing mass within 4th ventricle (3.5×3.0×2.8 cm) arising from the floor. Mild restricted diffusion. Hydrocephalus improved after EVD.', impression: 'Intraventricular tumor consistent with ependymoma. Surgical resection recommended.', linkedCaseId: 'BraTS2021_00014' },
      { id: 'img23', date: '2024-11-28', modality: 'MRI Brain Post-op', sequences: ['T1+Gd', 'FLAIR', 'DWI'], findings: 'Post-craniotomy changes. No residual enhancing tumor. 4th ventricle patent. EVD removed.', impression: 'Gross total resection confirmed. No hydrocephalus.', linkedCaseId: 'BraTS2021_00014' },
      { id: 'img24', date: '2024-12-05', modality: 'MRI Spine (staging)', sequences: ['T1+Gd', 'T2'], findings: 'No drop metastases. Normal spinal cord signal.', impression: 'No spinal dissemination. Important for ependymoma staging.' },
    ],
    allergies: [
      { id: 'a6', allergen: 'Latex', reaction: 'Contact dermatitis', severity: 'mild' },
    ],
    comorbidities: [],
    medications: [
      { id: 'm40', name: 'Mannitol', dosage: '100g', frequency: 'IV q8h PRN', startDate: '2024-11-22', endDate: '2024-11-25', notes: 'ICP management pre/peri-op' },
      { id: 'm41', name: 'Dexamethasone', dosage: '8 mg', frequency: 'IV q8h', startDate: '2024-11-22', endDate: '2024-12-05', notes: 'Posterior fossa edema, tapered' },
      { id: 'm42', name: 'Ceftriaxone', dosage: '2g', frequency: 'IV daily', startDate: '2024-11-23', endDate: '2024-11-30', notes: 'Post-op/EVD prophylaxis' },
      { id: 'm43', name: 'Ondansetron', dosage: '4 mg', frequency: 'PRN', startDate: '2024-11-22', notes: 'Anti-emetic' },
    ],
    visits: [
      { id: 'v32', date: '2024-11-22', department: 'Emergency / Neurosurgery', doctor: 'Dr. Fan Jun', diagnosis: 'Acute hydrocephalus from 4th ventricular mass', notes: 'Emergency EVD placed. ICP 32.' },
      { id: 'v33', date: '2024-11-24', department: 'Neurosurgery', doctor: 'Dr. Jiang Tao', diagnosis: 'Suboccipital craniotomy – GTR of ependymoma', notes: 'Successful GTR. Brainstem intact. EVD weaned.' },
      { id: 'v34', date: '2024-11-28', department: 'Neurosurgery', doctor: 'Dr. Jiang Tao', diagnosis: 'Post-op MRI: GTR confirmed', notes: 'EVD removed. Patient ambulatory, ataxia improving.' },
      { id: 'v35', date: '2024-12-05', department: 'Neuro-oncology', doctor: 'Dr. Xu Fang', diagnosis: 'Path: Ependymoma WHO II, PFB', notes: 'No chemo needed. Adjuvant RT 54 Gy planned. Spine MRI clear.' },
    ],
    files: [],
  },
];
